### PR TITLE
refactor: Update PoW contract address/ABI

### PR DESCRIPTION
**Pull request by DyepLucban**
### Review Type Requested (choose one):

- [x] **Glance** - superficial check (from domain experts)
- [] **Logic** - thorough check (from everybody doing review)

### Summary

Updated the PoW Contract address/ABI

### Task/Issue reference

Closes: [#89 ](https://github.com/Lilypad-Tech/web-ui/issues/89)

### CODE REVIEW

**Review by walkah — APPROVED** [review]
Excellent! This works for me 🚀 


Screenshot 2024-08-15 at 11 41 56 AM

**Comment by walkah** [comment]
@DyepLucban can you configure commit signatures and re-submit your changes? 🙏

**Comment by DyepLucban** [comment]
@walkah I'm closing this PR and making another [PR](https://github.com/Lilypad-Tech/web-ui/pull/90) for #89 . I don't know why I can't re-submit my commits 😓

**Comment by DyepLucban** [comment]
I'm closing this PR and making another PR [here](https://github.com/Lilypad-Tech/web-ui/pull/91) for #89 . I'm encountering unknown issue, that my local branch is not sync in main branch even if its updated. 😑

**Pull request closed without merging**
